### ISSUE TITLE
Crash when running from exFAT drive

### ISSUE THREAD

**Issue by Metaray** [colorer/FarColorer#71]
Plugin (and Far Manager) crashes when opening any file in the editor with FarColorer is installed.
FM is running from a flash drive formatted as exFAT. Problem doesn't happen if FM is copied and launched from NTFS drive. Searching for the error gives this:
https://developercommunity.visualstudio.com/t/std::filesystem::is_symlink-is-broken-on/1638272
https://www.boost.org/doc/libs/1_81_0/libs/filesystem/doc/release_history.html (search for "exFAT")

Crash log: [bug_report.txt](https://github.com/colorer/FarColorer/files/10299814/bug_report.txt)

**Comment by ctapmex** [comment]
https://github.com/colorer/Colorer-library/issues/26

**Comment by ctapmex** [comment]
fixed in 1.4.16

**Comment by MortenMacFly** [comment]
I am sorry to say this but for me, it is not fixed and keeps crashing (this plugin, version 1.4.16, Far32 and Far64, revision 6161).

**Comment by MortenMacFly** [comment]
[bug_report.txt](https://github.com/colorer/FarColorer/files/12224618/bug_report.txt)

**Comment by ctapmex** [comment]
@MortenMacFly  https://github.com/colorer/FarColorer/releases/tag/v1.4.16.3

**Comment by MortenMacFly** [comment]
> @MortenMacFly https://github.com/colorer/FarColorer/releases/tag/v1.4.16.3

OK, that really seems to work! Thank you!
