### ISSUE TITLE
Syntax highlighting not working for files without extension

### ISSUE THREAD

**Issue by rohitab** [colorer/FarColorer#80]
For files without extensions, syntax highlighting is no longer working, as the file type is not being detected.

For example, if you open `%WINDIR%\System32\drivers\etc\hosts`, the file will be detected as `default type` instead of `Config, INI and CTL`.  This was working in `v1.4.17` but stopped working in `v1.4.18`. The same happens with other file types.

Verified with Far Manager, version `3.0.6256.0 x64` and older versions.

**Comment by ctapmex** [comment]
fixed in [FarColorer v1.4.19](https://github.com/colorer/FarColorer/releases/tag/v1.4.19)

**Comment by rohitab** [comment]
@ctapmex this issue is back again. I tried both versions `1.4.0.20` and `1.4.0.21` in a new Far profile. I used the latest Far Manager, version `3.0.6274.0 x64`. FarColorer version `1.4.0.19` works correctly.

### Sample File for Testing
The attached file [`script.zip`](https://github.com/colorer/FarColorer/files/14307012/script.zip) contains two files - `script.sh` and `script`. Both files are identical, except for the `.sh` extension. The first file gets detected as a Bash script, while the second file, the one without the extension, gets detected as _default type_.

Please note that this issue is not limited to Bash files. Other files have the same issue.
